---
name: Application Build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [
            { name: 'macos',   image: 'macos-latest' }
          ]
        arch: [ 'arm64' ]
      fail-fast: false
          
    runs-on: ${{ matrix.os.image }}
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Corepack Enable Yarn
        run: corepack enable yarn
      - name: Setup Node (v20)
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: "20.9.0"
      - name: Install dependencies
        run: yarn --immutable
      - name: Build (arm64 - Production)
        env:
          YTMD_UPDATE_FEED_OWNER: ${{ vars.YTMD_UPDATE_FEED_OWNER }}
          YTMD_UPDATE_FEED_REPOSITORY: ${{ vars.YTMD_UPDATE_FEED_REPOSITORY }}
          NODE_ENV: production
        run: yarn make --arch arm64
      - name: Upload artifacts (arm64)
        uses: actions/upload-artifact@v4
        with:
          name: dist-macos-arm64
          path: |
            out/make/zip/darwin/arm64/*.zip
